### ISSUE TITLE
FileNotFoundError when loading clinlp_context_algorithm

### ISSUE THREAD

**Issue by vmenger** [umcu/clinlp#47]
Using the example from the readme, in pyton 3.11 and 3.12 the following error occurs: 

```
Traceback (most recent call last):
  File "/Users/username/Documents/clinlp_example.py", line 29, in <module>
    nlp.add_pipe("clinlp_context_algorithm", config={"phrase_matcher_attr": "NORM"})
  File "/Users/username/miniforge3/envs/debug/lib/python3.11/site-packages/spacy/language.py", line 821, in add_pipe
    pipe_component = self.create_pipe(
                     ^^^^^^^^^^^^^^^^^
  File "/Users/username/miniforge3/envs/debug/lib/python3.11/site-packages/spacy/language.py", line 709, in create_pipe
    resolved = registry.resolve(cfg, validate=validate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/miniforge3/envs/debug/lib/python3.11/site-packages/confection/__init__.py", line 756, in resolve
    resolved, _ = cls._make(
                  ^^^^^^^^^^
  File "/Users/username/miniforge3/envs/debug/lib/python3.11/site-packages/confection/__init__.py", line 805, in _make
    filled, _, resolved = cls._fill(
                          ^^^^^^^^^^
  File "/Users/username/miniforge3/envs/debug/lib/python3.11/site-packages/confection/__init__.py", line 877, in _fill
    getter_result = getter(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "<makefun-gen-2>", line 2, in make_component
  File "/Users/username/miniforge3/envs/debug/lib/python3.11/site-packages/clinlp/util.py", line 59, in make_component
    return cls(**cls_kwargs)
           ^^^^^^^^^^^^^^^^^
  File "/Users/username/miniforge3/envs/debug/lib/python3.11/site-packages/clinlp/qualifier/context_algorithm.py", line 132, in __init__
    rules = self._parse_rules(rules)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/miniforge3/envs/debug/lib/python3.11/site-packages/clinlp/qualifier/context_algorithm.py", line 203, in _parse_rules
    with open(rules, "rb") as file:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '<contextlib._GeneratorContextManager object at 0x1254bc850>'

```

**Comment by vmenger** [comment]
Fixed in #48.
